#!/usr/bin/env bash

# full-build-v2 – Build signed APK and AAB for Video Downloader
# ----------------------------------------------------
# This script automates the entire build pipeline so you can simply run:
#   full-build-v2
# and obtain ready‑to‑use .apk and .aab files.

set -euo pipefail

# ----- Configurable paths -----
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$PROJECT_ROOT/mobile"
ANDROID_DIR="$MOBILE_DIR/android"
KEYSTORE_ZIP="015-keystore.zip"
KEYSTORE_JKS="015-keystore.jks"
GRADLE_PROPERTIES="$ANDROID_DIR/gradle.properties"
OUTPUT_DIR="$PROJECT_ROOT/content"

# ----- Helper functions -----
log() { echo -e "\033[1;34m[full-build-v2] $*\033[0m"; }
error_exit() { echo -e "\033[1;31m[full-build-v2] ERROR: $*\033[0m"; exit 1; }

# 1️⃣ Ensure we are in the project root
log "Checking project structure…"
[[ -d "$MOBILE_DIR" && -f "$MOBILE_DIR/app.json" ]] || error_exit "Mobile directory not found."

# 2️⃣ Pre‑build Android native project
log "Running Expo prebuild (clean)…"
cd "$MOBILE_DIR"
npx expo prebuild --platform android --clean

# 3️⃣ Verify keystore presence (auto‑generate if missing)
log "Ensuring keystore exists…"
if [[ -f "$PROJECT_ROOT/$KEYSTORE_ZIP" ]]; then
  log "Unzipping $KEYSTORE_ZIP into android/…"
  cd "$ANDROID_DIR"
  unzip -o "$PROJECT_ROOT/$KEYSTORE_ZIP" -d .
else
  # Auto‑generate a keystore JKS with default credentials (can be overridden via env vars)
  log "Keystore zip not found – generating temporary keystore…"
  KEY_ALIAS=${KEY_ALIAS:-release_key}
  STORE_PASS=${STORE_PASS:-storepass123}
  KEY_PASS=${KEY_PASS:-keypass123}
  # Create JKS directly in android/ directory
  cd "$ANDROID_DIR"
  keytool -genkeypair -v \
    -keystore "$KEYSTORE_JKS" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$STORE_PASS" -keypass "$KEY_PASS" \
    -dname "CN=AutoGenerated, OU=Dev, O=VideoDownloader, L=City, S=State, C=XX"
  # Zip the generated keystore for future runs
  cd "$PROJECT_ROOT"
  zip -j "$KEYSTORE_ZIP" "mobile/android/$KEYSTORE_JKS"
  log "Generated $KEYSTORE_JKS and packaged as $KEYSTORE_ZIP"
fi

# 4️⃣ Create gradle.properties with actual values (auto‑filled if we just generated keystore)
log "Setting up gradle.properties…"
if [[ ! -f "$GRADLE_PROPERTIES" ]]; then
  cat > "$GRADLE_PROPERTIES" <<EOF
MYAPP_UPLOAD_STORE_FILE=$KEYSTORE_JKS
MYAPP_UPLOAD_KEY_ALIAS=${KEY_ALIAS:-release_key}
MYAPP_UPLOAD_STORE_PASSWORD=${STORE_PASS:-storepass123}
MYAPP_UPLOAD_KEY_PASSWORD=${KEY_PASS:-keypass123}
EOF
  log "Created $GRADLE_PROPERTIES with auto‑filled credentials."
else
  log "gradle.properties already exists – ensure it contains correct values."
fi

# 4.5️⃣ Setup local.properties for Android SDK
log "Setting up SDK location in local.properties…"
LOCAL_PROPS="$ANDROID_DIR/local.properties"
if [[ ! -f "$LOCAL_PROPS" ]]; then
  if [[ -n "${ANDROID_HOME:-}" ]]; then
    echo "sdk.dir=$ANDROID_HOME" > "$LOCAL_PROPS"
  else
    # Fallback to default Mac SDK path
    echo "sdk.dir=$HOME/Library/Android/sdk" > "$LOCAL_PROPS"
  fi
  log "Created $LOCAL_PROPS"
fi

# 5️⃣ Build signed APK and AAB
log "Building release APK and AAB…"
cd "$ANDROID_DIR"
./gradlew clean assembleRelease bundleRelease

# 6️⃣ Collect output
log "Collecting built APK and AAB…"
mkdir -p "$OUTPUT_DIR"
TIMESTAMP=$(date +%Y%m%d%H%M%S)

AAB_SRC="$ANDROID_DIR/app/build/outputs/bundle/release/app-release.aab"
APK_SRC="$ANDROID_DIR/app/build/outputs/apk/release/app-release.apk"

if [[ -f "$AAB_SRC" && -f "$APK_SRC" ]]; then
  cp "$AAB_SRC" "$OUTPUT_DIR/video-downloader-$TIMESTAMP.aab"
  cp "$APK_SRC" "$OUTPUT_DIR/video-downloader-$TIMESTAMP.apk"
  log "✅ APK and AAB created at $OUTPUT_DIR"
else
  error_exit "APK or AAB not found after build."
fi

log "Build completed successfully."
